In [22]:
import numpy as np   #importing the standard library numpy
#create an empty array of size 10, and reshape them in 1 block , 2 dimensions and 5 numbers in one row  
x = np.arange((10),dtype = np.float32).reshape(1,2,5)  
print(x)

[[[0. 1. 2. 3. 4.]
  [5. 6. 7. 8. 9.]]]


In [16]:
print(x.ndim)               #printing the dimensions of x
print(x.shape)              #print the shape of x that is 1,2,5
print(x.size)               #prints the size of the array , here 10
print(x.dtype.itemsize)     #prints the size of each itemtype in the array... here the datatype is 32 bit integer, so size will be 32 bits


3
(1, 2, 5)
10
4


In [27]:
z = np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
print("z is : ",z, "\n")
y = np.linspace(2, 11, 10, dtype = np.int64) #create an array with 10 elements from 2 to 11 and the datatype is a 64 bit integer
print("y is : ",y)

z is :  [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ] 

y is :  [ 2  3  4  5  6  7  8  9 10 11]


In [38]:
a = np.array([[10,20],          #2 blocks are required so we won't get an error
             [20,30]])
print("a is : \n",a)
print("shape of a is: ",a.shape)

a is : 
 [[10 20]
 [20 30]]
shape of a is:  (2, 2)


In [33]:
x = np.linspace(0, 2 * np.pi, 3)        #useful to evaluate function at lots of points
print("x = ", x,"\n")
f = np.sin(x)               #calculate the sine of each element and make an array of those values  
print("f is :",f) 

x =  [0.         3.14159265 6.28318531] 

f is : [ 0.0000000e+00  1.2246468e-16 -2.4492936e-16]


In [45]:
b = np.arange(20).reshape(5,4) #create an array b that ranges from 0 to 20 , and make it's shape of 5 rows and 4 columns
print("b is : \n",b,"\n") 
print("b squared is : \n",b ** 2) #calculate the power of each element and display the array

b is : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

b squared is : 
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]]


In [50]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((3, 3), dtype=int) #create a  3 X 3 array filled with 1
a *= 3
print("a is: \n",a,a.ndim,"\n")
b = rg.random((3, 3)) #creates a 3 by 3 array filled with random numbers 
print("b is: \n",b,"\n")
print("a + b is : \n",b + a,"\n")
# print("A dot B is: \n", a.dot(b),"\n")
print("A dot B is: \n", a @ b,"\n")

a is: 
 [[3 3 3]
 [3 3 3]
 [3 3 3]] 2 

b is: 
 [[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369]] 

a + b is : 
 [[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]
 [3.82770259 3.40919914 3.54959369]] 

A dot B is: 
 [[6.864521   5.01448285 3.35123925]
 [6.864521   5.01448285 3.35123925]
 [6.864521   5.01448285 3.35123925]] 

